### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by WillSmithTE** [NikhilModi488/Flight-Price-Prediction#2]
Hi, I was recently looking for a source of data for flights and flight prices similar to yours here. https://github.com/NikhilModi488/Flight-Price-Prediction/blob/main/Data_Train.csv

Do you mind sharing how you gathered your data? Do you have some kind of scraper implemented? Thanks!

**Comment by NikhilModi488** [comment]
> Hi, I was recently looking for a source of data for flights and flight prices similar to yours here. https://github.com/NikhilModi488/Flight-Price-Prediction/blob/main/Data_Train.csv
> 
> Do you mind sharing how you gathered your data? Do you have some kind of scraper implemented? Thanks!

dataset link: https://www.kaggle.com/datasets/nikhilmittal/flight-fare-prediction-mh
